// Seed data ported from Brown_Family_Budget_EveryDollar.xlsx (June 2026 sheet)
let n = 0
const id = () => `seed-${++n}`

// due: day-of-month (1-31) or '' for no fixed due date
const item = (name, due, planned) => ({
  id: id(),
  name,
  due,
  planned,
  spent: 0,
  paid: false,
  balance: 0,
  apr: 0,
})

export function seedJune2026() {
  n = 0
  return {
    label: 'June 2026',
    income: [
      { id: id(), name: 'Jarrod 1st Paycheck', planned: 4145 },
      { id: id(), name: 'Jarrod 2nd Paycheck', planned: 4145 },
      { id: id(), name: 'Jarrod VA Benefits', planned: 2802.3 },
    ],
    transactions: [],
    accountNotes: {},
    groups: [
      {
        id: id(),
        name: 'Giving / Generosity',
        account: 'USAA – 3399',
        items: [item('LakePointe', 15, 1150), item('Generosity', '', 33.81)],
      },
      {
        id: id(),
        name: 'Monthly Expenses',
        account: 'USAA – 3399',
        items: [
          item('Groceries', '', 1077.68),
          item('Beauty/Body Care', '', 40),
          item('Family Fun', '', 60),
          item('Eating Out', '', 60),
          item('Petrol', '', 160),
          item('J & A Dates', '', 80),
          item('J & V Dates', '', 40),
          item('J & P Dates', '', 40),
          item('LG Fellowship', '', 80),
          item('Spiritual Growth Meetings', '', 30),
        ],
      },
      {
        id: id(),
        name: 'Monthly Bills',
        account: 'USAA – 3399',
        items: [
          item('M&T Mortgage', 1, 2742.65),
          item('M&T Extra House Payment', '', 200),
          item('Rockwall Utilities', 16, 125),
          item('Atmos Gas', 14, 50.08),
          item('Lawn Care - Grass/Weeds', '', 45),
          item('Lawn Care - Mowing', '', 120),
          item('FEC Electric', 28, 200),
          item('AT&T Internet', 27, 95.9),
          item('AT&T Cell', 27, 192.25),
          item('Pet Waste Disposal', '', 40),
        ],
      },
      {
        id: id(),
        name: 'Insurances',
        account: 'USAA – 3399',
        items: [
          item('USAA Life Insurance - JB #1', '', 77.98),
          item('USAA Life Insurance - JB #2', '', 32.49),
          item('USAA Bundled Insurance', '', 473.01),
          item('USAA Life Insurance - AB', '', 66),
          item('Zander ID Insurance', '', 12.9),
        ],
      },
      {
        id: id(),
        name: 'Subscriptions',
        account: 'USAA – 3399',
        items: [
          item('Nintendo', '', 8.49),
          item('Amazon Prime Video', '', 12.97),
          item('Spotify Music', '', 23.8),
          item('Office 365', '', 14.06),
          item('iCloud', '', 10),
          item('CineMark Movies', '', 23.8),
          item('Netflix', 16, 19.47),
          item('Peacock Streaming', '', 18.39),
          item('Ring Camera', '', 10.81),
          item('Eero Security', '', 10.65),
          item('Life360', '', 14.99),
          item('Disney/Hulu Bundle', '', 21.64),
          item('1Password App', 23, 4),
          item('Paramount Plus & Showtime', '', 6.49),
          item('YouTube Premium', '', 17.99),
          item('Claude Pro', '', 20),
        ],
      },
      {
        id: id(),
        name: 'Digital Envelopes / Sinking Funds',
        account: 'USAA – 3399',
        rollover: true,
        items: [
          item('Christmas', '', 150),
          item('Family Vacation', '', 5),
          item('J & A Special Occasion', '', 295),
          item('Jarrod Misc.', '', 125),
          item('Amanda Misc.', '', 125),
          item('Birthdays/Special Occasion', '', 205),
          item('Clothes/Shoes', '', 100),
          item('Piper Allowance', '', 50),
          item('Hair', '', 100),
          item('Pet Grooming & Vet', '', 150),
          item('Pet Food', '', 30),
          item('Hosting/Generosity', '', 0),
          item("Kid's School", '', 0),
          item('Dental/Health Expenses', '', 0),
          item('HOA Dues', '', 45),
          item('Vehicle Expenses', '', 200),
        ],
      },
      {
        id: id(),
        name: 'To Emergency Fund',
        account: 'Ally – 8204',
        rollover: true,
        items: [item('Emergency Fund', '', 500)],
      },
      {
        id: id(),
        name: 'To Ally Savings',
        account: 'Ally – 8196',
        rollover: true,
        items: [
          item('Vehicle Sinking', '', 0),
          item('House Maintenance', '', 100),
          item('College', '', 500),
          item("Piper's Graduation Trip", '', 100),
          item('England Vacation', '', 100),
          item('J & A Roth IRAs', '', 650),
        ],
      },
      {
        id: id(),
        name: 'Debt',
        account: 'Baby Step 2 – smallest balance first',
        items: [],
      },
    ],
  }
}
